flaskdb/flaskdb/views.py
"""
A Sample Web-DB Application for DB-DESIGN lecture
Copyright (C) 2022 Yasuhiro Hayashi
"""
from flask import Blueprint, request, session, render_template, redirect, flash, url_for
from werkzeug.security import generate_password_hash, check_password_hash
import datetime
import pickle

from flaskdb import apps, db, da
from flaskdb.models import User, Item
from flaskdb.forms import LoginForm, AddItemForm, SearchItemForm, SignUpForm

app = Blueprint("app", __name__)

@app.route("/", methods=["GET", "POST"])
def index():
    return render_template("/index.html")

@app.route("/now", methods=["GET", "POST"])
def now():
    return str(datetime.datetime.now())

# This is a very danger method
# @app.route("/receive", methods=["GET", "POST"])
# def receive():
#     if request.method == "GET":
#         username = request.args.get("username")
#         password = request.args.get("password")
#     else:
#         username = request.form["username"]
#         password = request.form["password"]

#     return render_template("receive.html", username=username, password=password)

@app.route("/initdb", methods=["GET", "POST"])
def initdb():
    db.drop_all()
    db.create_all()
    
    keita = User(loginID=2022038,grade=3,groupnumber=1, username="keita", password="password")
    db.session.add(keita)
    db.session.commit()
    return "initidb() method was executed. "

@app.route('/signup', methods=['GET', 'POST'])
def signup():
    form = SignUpForm()

    if form.validate_on_submit():
        grade = request.form.get('grade')
        groupnumber = request.form.get('groupnumber')
        user = User(loginID=form.loginID.data,grade=grade,groupnumber=groupnumber,username=form.username.data,password=form.password.data)
        # Userのインスタンスを作成
        db.session.add(user)
        #db.session.bulk_save_objects(user, update_changed_only=False)
        db.session.commit()
        #flash('Congratulations, you are now a registered user!')
        return redirect(url_for('app.login'))
  # ユーザーが未ログインまたはバリデーションエラーの場合、ユーザー登録ページにリダイレクト
    return render_template('signup.html', form=form)
   

@app.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        # print(form.loginID.data)
        # print(form.password.data)
        user = User.query.filter_by(loginID=form.loginID.data).first()

        if user is None or user.password != form.password.data:
            flash("loginID or Password is incorrect.", "danger")
            return redirect(url_for("app.login"))


        session["loginID"] = user.loginID
        session["name"] = user.username
        session["grade"] = user.grade
        session["groupnumber"] = user.groupnumber
        # userinfo = User.query.filter(User.loginID.like("%" + form.loginID.data + "%")).all()  
        return redirect(url_for("app.index"))
    return render_template("login.html", form=form)

@app.route("/logout", methods=["GET", "POST"])
def logout():
    session.pop("loginID", None)
    session.clear()
    flash("You have been logged out.", "info")
    return redirect(url_for("app.index"))

@app.route("/additem", methods=["GET", "POST"])
def additem():
    if not "username" in session:
        flash("Log in is required.", "danger")
        return redirect(url_for("app.login"))

    form = AddItemForm()

    if form.validate_on_submit():
        item = Item()
        form.copy_to(item)
        user = User.query.filter_by(username=session["username"]).first()
        item.user_id = user.id
        db.session.add(item)
        db.session.commit()

        flash("An item was added.", "info")
        return redirect(url_for("app.additem"))

    itemlist = Item.query.all()
    return render_template("additem.html", form=form, itemlist=itemlist)

@app.route("/searchitem", methods=["GET", "POST"])
def searchitem():
    if not "username" in session:
        flash("Log in is required.", "danger")
        return redirect(url_for("app.login"))

    form = SearchItemForm()

    if form.validate_on_submit():
        itemlist = Item.query.filter(Item.itemname.like("%" + form.itemname.data + "%")).all()        
        return render_template("search.html", form=form, itemlist=itemlist)

        # For change to PRG
        # itemlist = pickle.dumps(itemlist)
        # session["itemlist"] = itemlist
        # return redirect(url_for("app.searchitem"))

    # if "itemlist" in session:
    #     itemlist = session["itemlist"]
    #     itemlist = pickle.loads(itemlist)
    #     session.pop("itemlist", None)
    # else:
    #     itemlist = None
    # 
    # return render_template("search.html", form=form, itemlist=itemlist)

    return render_template("search.html", form=form)

@app.route("/nativesql", methods=["GET", "POST"])
def nativesql():
    if not "username" in session:
        flash("Log in is required.", "danger")
        return redirect(url_for("app.login"))

    form = AddItemForm()

    if form.validate_on_submit():
        item = Item()
        form.copy_to(item)
        user = User.query.filter_by(username=session["username"]).first()
        item.user_id = user.id
        da.add_item(item)

        flash("An item was added.", "info")
        return redirect(url_for("app.additem"))

    itemlist = da.search_items()
    return render_template("additem.html", form=form, itemlist=itemlist)

flaskdb/flaskdb/templates/index.html
{% extends "bootstrap/base.html" %}

{% block head %}
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>flaskdb | Index</title>
  <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/css/flaskdb.css" rel="stylesheet">
  <!-- A Sample Web-DB Application for DB-DESIGN lecture -->
  <!-- Copyright (C) 2022 Yasuhiro Hayashi -->
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('app.index') }}">flaskdb</a>
    </div>
    <div class="navbar-collapse collapse"> 
      <ul class="nav navbar-nav">
        {% if not "loginID" in session %}
        <li><a href="{{ url_for('app.login') }}">Login</a></li>
        {% else %}
        <li><a href="{{ url_for('app.additem') }}">Add Item</a></li>
        <li><a href="{{ url_for('app.searchitem') }}">Search Item</a></li>
        <li><a href="{{ url_for('app.logout') }}">Logout</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
  <div class="page-header"><h1>Index</h1></div>
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{ category }}"> {{ message|capitalize }} </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  {% if form %}
    {% for field in form.errors %}
      {% for error in form.errors[field] %}
        <div class="alert alert-danger">{{ error }}</div>
      {% endfor %}
    {% endfor %}
  {% endif %}
  {% if "loginID" in session %}
  <p>Welcome, {{ session["name"] }}!</p>
  {% endif %}
</div>
{% endblock %}

{% block scripts %}
<script src="{{ bootstrap_find_resource('jquery.js', cdn='jquery') }}"></script>
<script src="{{ bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap') }}"></script>
<script src="/static/js/flaskdb.js"></script>
{% endblock %}

flaskdb/flaskdb/templates/receive.html
<!DOCTYPE html>
<html>
<head>
<title>flaskdb | receive</title>
<!-- A Sample Web-DB Application for DB-DESIGN lecture -->
<!-- Copyright (C) 2022 Yasuhiro Hayashi -->
</head>
<body>

<h2>GET:</h2>
<div><a href="{{ url_for('app.receive') }}">{{ url_for('app.receive') }}</a></div>
<div><a href="{{ url_for('app.receive') }}?username=taro&password=password">{{ url_for('app.receive') }}?username=taro&password=password</a></div>
<br>
<br>
<br>

<h2>POST:</h2>
<form action="{{ url_for('app.receive') }}" method="POST">
<input type="text" name="username" placeholder="Input your name">
<input type="password" name="password" placeholder="Input your password">
<button type="button">Cancel</button>
<input type="submit" value="Login">
</form>
<br>
<br>
<br>

<h2>Received Data:</h2>
<div>username: {{ username }}</div>
<div>password: {{ password }}</div>

</body>
</html>