flaskdb2/flaskdb/views.py
"""
A Sample Web-DB Application for DB-DESIGN lecture
Copyright (C) 2022 Yasuhiro Hayashi
"""
#from msvcrt import open_osfhandle
from pipes import quote
from flask import Blueprint, request, session, render_template, redirect, flash, url_for
from werkzeug.security import generate_password_hash, check_password_hash
import datetime
import pickle
import pandas as pd
import numpy as np

from flaskdb import apps, db, da
from flaskdb.models import User, Item, Form1,Test
from flaskdb.forms import LoginForm, AddItemForm, SearchItemForm, SignUpForm,Form1Form


app = Blueprint("app", __name__)



      
@app.route("/", methods=["GET", "POST"])
def index():
    return render_template('index.html')

@app.route("/now", methods=["GET", "POST"])
def now():
    return str(datetime.datetime.now())

# This is a very danger method
# @app.route("/receive", methods=["GET", "POST"])
# def receive():
#     if request.method == "GET":
#         username = request.args.get("username")
#         password = request.args.get("password")
#     else:
#         username = request.form["username"]
#         password = request.form["password"]

#     return render_template("receive.html", username=username, password=password)

@app.route("/initdb", methods=["GET", "POST"])
def initdb():
    db.drop_all()
    db.create_all()
    
    keita = User(loginID=2022038,grade=3,groupnumber=1, username="keita", password="password")
    db.session.add(keita)
    db.session.commit()
    return "initidb() method was executed. "

@app.route('/signup', methods=['GET', 'POST'])
def signup():
    form = SignUpForm()

    if form.validate_on_submit():
        grade = request.form.get('grade')
        groupnumber = request.form.get('groupnumber')
        user = User(loginID=form.loginID.data,grade=grade,groupnumber=groupnumber,username=form.username.data,password=form.password.data)
        # Userのインスタンスを作成
        db.session.add(user)
        #db.session.bulk_save_objects(user, update_changed_only=False)
        db.session.commit()
        #flash('Congratulations, you are now a registered user!')
        return redirect(url_for('app.login'))
  # ユーザーが未ログインまたはバリデーションエラーの場合、ユーザー登録ページにリダイレクト
    return render_template('signup.html', form=form)
   

@app.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        # print(form.loginID.data)
        # print(form.password.data)
        user = User.query.filter_by(loginID=form.loginID.data).first()

        if user is None or user.password != form.password.data:
            flash("loginID or Password is incorrect.", "danger")
            return redirect(url_for("app.login"))


        session["loginID"] = user.loginID
        session["name"] = user.username
        session["grade"] = user.grade
        session["groupnumber"] = user.groupnumber
        # userinfo = User.query.filter(User.loginID.like("%" + form.loginID.data + "%")).all()  
        return redirect(url_for("app.calendar",grade=session["grade"] ,groupnumber=session["groupnumber"]))
    return render_template("login.html", form=form)

@app.route("/calendar",methods=["GET","POST"])
def calendar():
    form1 = Form1.query.all()
    userID = []
    mon_1 = []
    mon_2 = []
    mon_3 = []
    mon_4 = []
    mon_5 = []
    mon_6 = []
    tue_1 = []
    tue_2 = []
    tue_3 = []
    tue_4 = []
    tue_5 = []
    tue_6 = []
    wen_1 = []
    wen_2 = []
    wen_3 = []
    wen_4 = []
    wen_5 = []
    wen_6 = []
    thu_1 = []
    thu_2 = []
    thu_3 = []
    thu_4 = []
    thu_5 = []
    thu_6 = []
    fri_1 = []
    fri_2 = []
    fri_3 = []
    fri_4 = []
    fri_5 = []
    fri_6 = []
    for data in form1:
        userID.append(str(data.loginID))
        mon_1.append(str(data.mon_1))
        mon_2.append(str(data.mon_2))
        mon_3.append(str(data.mon_3))
        mon_4.append(str(data.mon_4))
        mon_5.append(str(data.mon_5))
        mon_6.append(str(data.mon_6))
        tue_1.append(str(data.tue_1))
        tue_2.append(str(data.tue_2))
        tue_3.append(str(data.tue_3))
        tue_4.append(str(data.tue_4))
        tue_5.append(str(data.tue_5))
        tue_6.append(str(data.tue_6))
        wen_1.append(str(data.wen_1))
        wen_2.append(str(data.wen_2))
        wen_3.append(str(data.wen_3))
        wen_4.append(str(data.wen_4))
        wen_5.append(str(data.wen_5))
        wen_6.append(str(data.wen_6))
        thu_1.append(str(data.thu_1))
        thu_2.append(str(data.thu_2))
        thu_3.append(str(data.thu_3))
        thu_4.append(str(data.thu_4))
        thu_5.append(str(data.thu_5))
        thu_6.append(str(data.thu_6))
        fri_1.append(str(data.fri_1))
        fri_2.append(str(data.fri_2))
        fri_3.append(str(data.fri_3))
        fri_4.append(str(data.fri_4))
        fri_5.append(str(data.fri_5))
        fri_6.append(str(data.fri_6))

    df = pd.DataFrame(mon_1,columns=['mon-1'],index=userID)

    df['mon-2'] = mon_2
    df['mon-3'] = mon_3
    df['mon-4'] = mon_4
    df['mon-5'] = mon_5
    df['mon-4'] = mon_4
    df['mon-5'] = mon_5
    df['mon-6'] = mon_6
    df['tue-1'] = tue_1
    df['tue-2'] = tue_2
    df['tue-3'] = tue_3
    df['tue-4'] = tue_4
    df['tue-5'] = tue_5
    df['tue-6'] = tue_6
    df['wen-1'] = wen_1
    df['wen-2'] = wen_2
    df['wen-3'] = wen_3
    df['wen-4'] = wen_4
    df['wen-5'] = wen_5
    df['wen-6'] = wen_6
    df['thu-1'] = thu_1
    df['thu-2'] = thu_2
    df['thu-3'] = thu_3
    df['thu-4'] = thu_4
    df['thu-5'] = thu_5
    df['thu-6'] = thu_6
    df['fri-1'] = fri_1
    df['fri-2'] = fri_2
    df['fri-3'] = fri_3
    df['fri-4'] = fri_4
    df['fri-5'] = fri_5
    df['fri-6'] = fri_6

    df[['mon-1','mon-2','mon-3','mon-4','mon-5','mon-6','tue-1','tue-2','tue-3','tue-4','tue-5','tue-6','wen-1','wen-2','wen-3','wen-4','wen-5','wen-6','thu-1','thu-2','thu-3','thu-4','thu-5','thu-6','fri-1','fri-2','fri-3','fri-4','fri-5','fri-6']] = df[['mon-1','mon-2','mon-3','mon-4','mon-5','mon-6','tue-1','tue-2','tue-3','tue-4','tue-5','tue-6','wen-1','wen-2','wen-3','wen-4','wen-5','wen-6','thu-1','thu-2','thu-3','thu-4','thu-5','thu-6','fri-1','fri-2','fri-3','fri-4','fri-5','fri-6']].astype(int)
    df2 = df.T
    # df2.sum(axis = 'columns')

    df2['sum'] = df2.sum(axis =1)

    # print(df2[df2['sum']>4])
    # print(df2['sum']>4)
    dos = len(df['mon-1'])
    reqd_Index = df2[df2['sum']>=dos].index.tolist()

    d={'mon-1':'08:50~10:30', 'mon-2':'10:40~12:20','mon-3':'13:10~14:50','mon-4':'15:00~16:40','mon-5':'16:50~18:30','mon-6':'18:40~20:20',
    'tue-1':'08:50~10:30', 'tue-2':'10:40~12:20','tue-3':'13:10~14:50','tue-4':'15:00~16:40','tue-5':'16:50~18:30','tue-6':'18:40~20:20',
    'wen-1':'08:50~10:30', 'wen-2':'10:40~12:20','wen-3':'13:10~14:50','wen-4':'15:00~16:40','wen-5':'16:50~18:30','wen-6':'18:40~20:20',
    'thu-1':'08:50~10:30', 'thu-2':'10:40~12:20','thu-3':'13:10~14:50','thu-4':'15:00~16:40','thu-5':'16:50~18:30','thu-6':'18:40~20:20',
    'fri-1':'08:50~10:30', 'fri-2':'10:40~12:20','fri-3':'13:10~14:50','fri-4':'15:00~16:40','fri-5':'16:50~18:30','fri-6':'18:40~20:20'}
    pp = []
    ss = []
    for i in reqd_Index:
        pp.append(i)
        ss.append(d[i])

    mond = []
    tusd = []
    wend = []
    thur = []
    frid = []
    for j in pp:
        if 'mon' in j:
            mond.append(j)
        if 'tue' in j:
            tusd.append(j)
        if 'wen' in j:
            wend.append(j)
        if 'thu' in j :
            thur.append(j)
        if 'fri' in j :
            frid.append(j)
    sssl=[]
    pso = []
    sssf =[]
    ssds = []
    sssd = []
    for q in mond:
        sssl.append(d[q])
    for q in tusd:
        pso.append(d[q])
    for q in wend:
        sssf.append(d[q])
    for q in thur:
        ssds.append(d[q])
    for q in frid:
        sssd.append(d[q])


    i1 = sssl*7
    i1.sort()
    i2 = pso*7
    i2.sort()
    i3 = sssf*7
    i3.sort()
    i4 = ssds*7
    i4.sort()
    i5 = sssd*7
    i5.sort()


    montt = ['2022-09-26','2022-10-03','2022-10-17','2022-10-24','2022-10-31','2022-11-07','2022-11-14']
    tuett = ['2022-09-27','2022-10-04','2022-10-11','2022-10-18','2022-10-25','2022-11-01','2022-11-08']
    wentt = ['2022-09-28','2022-10-05','2022-10-12','2022-10-19','2022-10-26','2022-11-02','2022-11-09']
    thutt = ['2022-09-29','2022-10-06','2022-10-13','2022-10-20','2022-10-27','2022-11-03','2022-11-10']
    fritt = ['2022-09-23','2022-09-30','2022-10-14','2022-10-21','2022-10-28','2022-11-04','2022-11-11']
    kk = []
    for i in pp:
        if 'mon' in i:
            kk.extend(montt)
        if 'tue' in i:
            kk.extend(tuett)
        if 'wen' in i:
            kk.extend(wentt)
        if 'thu' in i:
            kk.extend(thutt)
        if 'fri' in i:
            kk.extend(fritt)

    u1 = i1 + i2 + i3 + i4 + i5

    events = []
    for (titles,date) in zip(u1,kk):
        events.append(
                {
                    "title": titles,
                    "date": date
                }
                
        )

    return render_template('calendar.html',events=events)



@app.route("/form1", methods=["GET", "POST"])
def form1():
    if request.method =='POST':
        name = request.form.getlist('checkbox')
        pp = []
        pp.clear()
        for x in range(1,31):
            if str(x) in name:
                pp.append(1)
            else:
                pp.append(0)
        ss = Form1(loginID=session['loginID'],mon_1=pp[0],
            mon_2=pp[1],
            mon_3=pp[2]
            ,mon_4=pp[3]
            ,mon_5=pp[4],
            mon_6=pp[5],
            tue_1=pp[6],
            tue_2=pp[7],
            tue_3=pp[8],
            tue_4=pp[9],
            tue_5=pp[10],
            tue_6=pp[11],
            wen_1=pp[12],
            wen_2=pp[13],
            wen_3=pp[14],
            wen_4=pp[15],
            wen_5=pp[16],
            wen_6=pp[17],
            thu_1=pp[18],
            thu_2=pp[19],
            thu_3=pp[20],
            thu_4=pp[21],

flaskdb2/flaskdb/templates/calendar.html
{% extends "bootstrap/base.html" %}

{% block head %}
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>flaskdb | calendar</title>
    <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/flaskdb.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.5.0/main.min.css">
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.5.0/main.min.js"></script>
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('app.index') }}">flaskdb</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
            {% if not "loginID" in session %}
            <li><a href="{{ url_for('app.signup') }}">SignUP</a></li>
            {% else %}
            <li><a href="{{ url_for('app.calendar') }}">Your calendar</a></li>
            <li><a href="{{ url_for('app.form1') }}">空きこま入力</a></li>
            <li><a href="{{ url_for('app.logout') }}">Logout</a></li>
            {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}


{% block content %}
        {% if "loginID" in session %}
            <h2>Welcome, {{ session["name"] }}!</h2>
            <h3>あなたのグループは{{ session["groupnumber"] }}です。</h3>
        {% endif %}
<div class="container">
    <div class="row">
        <div class="col-12 col-md-3">
            <div class="card" style="width: 18rem;">
                <div class="card-header">
                <h5>日程調整フォーム</h5>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><a href="#">１週目</a></li>
                    <li class="list-group-item"><a href="#">２週目</a></li>
                    <li class="list-group-item"><a href="#">３週目</a></li>
                    <li class="list-group-item"><a href="#">４週目</a></li>

                </ul>
            </div>
        </div>
        <div class="col-12 col-md-9" id="calendar">
            <script>
                let calendarEl = document.getElementById('calendar');
                let calendar = new FullCalendar.Calendar(calendarEl, {
                    events: [
                    {% for event in events %}
                    {
                        title: '{{ event.title }}',
                        start: '{{ event.date }}',
                    },
                    {% endfor %}
                    ]
                });
                                            
                calendar.render();

            </script>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{{ bootstrap_find_resource('jquery.js', cdn='jquery') }}"></script>
<script src="{{ bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap') }}"></script>
<script src="/static/js/flaskdb.js"></script>
{% endblock %}

flaskdb2/flaskdb/templates/calendar31.html
{% extends "bootstrap/base.html" %}

{% block head %}
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>flaskdb | calendar</title>
    <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/flaskdb.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.5.0/main.min.css">
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.5.0/main.min.js"></script>
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('app.index') }}">flaskdb</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
            {% if not "loginID" in session %}
            <li><a href="{{ url_for('app.signup') }}">SignUP</a></li>
            {% else %}
            <li><a href="{{ url_for('app.additem') }}">Add Item</a></li>
            <li><a href="{{ url_for('app.searchitem') }}">Search Item</a></li>
            <li><a href="{{ url_for('app.logout') }}">Logout</a></li>
            {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}


{% block content %}
        {% if "loginID" in session %}
            <h2>Welcome, {{ session["name"] }}!</h2>
            <h3>あなたのグループは{{ session["groupnumber"] }}です。</h3>
        {% endif %}

<div class="container">
    <div class="row">
        <div class="col-12 col-md-3">
            <div class="card" style="width: 18rem;">
                <div class="card-header">
                <h5>日程調整フォーム</h5>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><a href="{{ url_for('app.form1') }}">１週目</a></li>
                    <li class="list-group-item"><a href="#">２週目</a></li>
                    <li class="list-group-item"><a href="#">３週目</a></li>
                    <li class="list-group-item"><a href="#">４週目</a></li>

                </ul>
            </div>
        </div>
        <div class="col-12 col-md-9" id="calendar">
            <script>
                let calendarEl = document.getElementById('calendar');

                let calendar = new FullCalendar.Calendar(calendarEl, {
                    events: [
                    {% for event in events %}
                    {
                        title: '{{ event.title }}',
                        start: '{{ event.date }}',
                    },
                    {% endfor %}
                    ]
                });

                calendar.render();

            </script>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{{ bootstrap_find_resource('jquery.js', cdn='jquery') }}"></script>
<script src="{{ bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap') }}"></script>
<script src="/static/js/flaskdb.js"></script>
{% endblock %}

flaskdb2/flaskdb/templates/index.html
{% extends "bootstrap/base.html" %}

{% block head %}
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>flaskdb | Index</title>
  <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/css/flaskdb.css" rel="stylesheet">
  <!-- A Sample Web-DB Application for DB-DESIGN lecture -->
  <!-- Copyright (C) 2022 Yasuhiro Hayashi -->
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('app.index') }}">flaskdb</a>
    </div>
    <div class="navbar-collapse collapse"> 
      <ul class="nav navbar-nav">
        {% if not "loginID" in session %}
        <li><a href="{{ url_for('app.login') }}">Login</a></li>
        {% else %}
        <li><a href="{{ url_for('app.calendar') }}">Your calendar</a></li>
        <li><a href="{{ url_for('app.form1') }}">空きこま入力</a></li>
        <li><a href="{{ url_for('app.logout') }}">Logout</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
  <div class="page-header"><h1>Index</h1></div>
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{ category }}"> {{ message|capitalize }} </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  {% if form %}
    {% for field in form.errors %}
      {% for error in form.errors[field] %}
        <div class="alert alert-danger">{{ error }}</div>
      {% endfor %}
    {% endfor %}
  {% endif %}
  {% if "loginID" in session %}
  <p>Welcome, {{ session["name"] }}!</p>
  <p>あなたのグループは{{ session["groupnumber"] }}です。</p>
  {% endif %}
{% endblock %}

{% block scripts %}
<script src="{{ bootstrap_find_resource('jquery.js', cdn='jquery') }}"></script>
<script src="{{ bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap') }}"></script>
<script src="/static/js/flaskdb.js"></script>
{% endblock %}

flaskdb2/flaskdb/templates/login.html
{% extends "bootstrap/base.html" %}

{% block head %}
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>flaskdb | Index</title>
  <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/css/flaskdb.css" rel="stylesheet">
  <!-- A Sample Web-DB Application for DB-DESIGN lecture -->
  <!-- Copyright (C) 2022 Yasuhiro Hayashi -->
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('app.index') }}">flaskdb</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        {% if not "loginID" in session %}
        <li><a href="{{ url_for('app.signup') }}">SignUP</a></li>
        {% else %}
        <li><a href="{{ url_for('app.additem') }}">Add Item</a></li>
        <li><a href="{{ url_for('app.searchitem') }}">Search Item</a></li>
        <li><a href="{{ url_for('app.logout') }}">Logout</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
  <div class="page-header"><h1>Login</h1></div>
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{ category }}"> {{ message|capitalize }} </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  {% if form %}
    {% for field in form.errors %}
      {% for error in form.errors[field] %}
        <div class="alert alert-danger">{{ error }}</div>
      {% endfor %}
    {% endfor %}
  {% endif %}
  <form action="{{ url_for('app.login') }}" method="POST" novalidate class="mb-10">
    <!-- <div class="form-group">
      <label for="loginID">{{ form.loginID.label }}</label>
      {{ form.username(type="text", id="loginID", class="form-control", placeholder="Enter your username") }}
    </div>
    <div class="form-group">
      <label for="password">{{ form.password.label }}</label>
      {{ form.password(type="password", id="password", class="form-control", placeholder="Enter your password") }}
    </div> -->
    <div class="form-group">
      <label for="loginID">{{ form.loginID.label }}</label>
      {{ form.loginID(type="text", id="loginID", class="form-control", placeholder="Enter your loginID") }}
    </div>
    <div class="form-group">
      <label for="password">{{ form.password.label }}</label>
      {{ form.password(type="password", id="password", class="form-control", placeholder="Enter your password") }}
    </div>
    {{ form.csrf_token }}
    {{ form.cancel(class="btn") }}
    {{ form.submit(class="btn btn-primary") }}
  </form>
</div>
{% endblock %}

{% block scripts %}
<script src="{{ bootstrap_find_resource('jquery.js', cdn='jquery') }}"></script>
<script src="{{ bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap') }}"></script>
<script src="/static/js/flaskdb.js"></script>
{% endblock %}

flaskdb2/flaskdb/templates/signup.html
{% extends "bootstrap/base.html" %}

{% block head %}
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>flaskdb | Index</title>
  <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/css/flaskdb.css" rel="stylesheet">
  <!-- A Sample Web-DB Application for DB-DESIGN lecture -->
  <!-- Copyright (C) 2022 Yasuhiro Hayashi -->
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('app.index') }}">flaskdb</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="{{ url_for('app.login') }}">Login</a></li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
  <div class="page-header"><h1>SignUP</h1></div>
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{ category }}"> {{ message|capitalize }} </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  {% if form %}
    {% for field in form.errors %}
      {% for error in form.errors[field] %}
        <div class="alert alert-danger">{{ error }}</div>
      {% endfor %}
    {% endfor %}
  {% endif %}
  <form action="{{ url_for('app.signup') }}" method="POST" novalidate class="mb-10">
    <div class="form-group">
      <label for="loginID">{{ form.loginID.label }}</label>
      {{ form.loginID(type="text", id="loginID", class="form-control", placeholder="Enter your loginID") }}
    </div>
    <div class="form-group">
      <label for="grade">{{ form.grade.label }}</label>
      <select name="grade">
        <option value="null" disabled selected>選択して下さい</option>
        <option value=1>1年</option>
        <option value=2>2年</option>
        <option value=3>3年</option>
        <option value=4>4年</option>
      </select>
    </div>
    <div class="form-group">
      <label for="groupnumber">{{ form.groupnumber.label }}</label>
      <select name="groupnumber">
        <option value="null" disabled selected>選択して下さい</option>
        <option value=1>1</option>
        <option value=2>2</option>
        <option value=3>3</option>
        <option value=4>4</option>
        <option value=5>5</option>
        <option value=6>6</option>
        <option value=7>7</option>
        <option value=8>8</option>
        <option value=9>9</option>
        <option value=10>10</option>
        <option value=11>11</option>
        <option value=12>12</option>
        <option value=13>13</option>
        <option value=14>14</option>
        <option value=15>15</option>
        <option value=16>16</option>
        <option value=17>17</option>
        <option value=18>18</option>
        <option value=19>19</option>
        <option value=20>20</option>
        <option value=21>21</option>
        <option value=22>22</option>
        <option value=23>23</option>
      </select>
    </div>
    <div class="form-group">
      <label for="username">{{ form.username.label }}</label>
      {{ form.username(type="text", id="username", class="form-control", placeholder="Enter your username") }}
    </div>
    <div class="form-group">
      <label for="password">{{ form.password.label }}</label>
      {{ form.password(type="password", id="password", class="form-control", placeholder="Enter your password") }}
    </div>
    {{ form.csrf_token }}
    {{ form.cancel(class="btn") }}
    {{ form.submit(class="btn btn-primary") }}
  </form>
</div>
{% endblock %}

{% block scripts %}
<script src="{{ bootstrap_find_resource('jquery.js', cdn='jquery') }}"></script>
<script src="{{ bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap') }}"></script>
<script src="/static/js/flaskdb.js"></script>
{% endblock %}